(()=>{'use strict';const $=id=>document.getElementById(id);let pet='cat',lastUnits='kg',shareText='';
function calculate(initial=false){const f=$('food').value;const wetShare=f==='dry'?0:f==='wet'?1:Number($('split').value)/100;$('split-wrap').hidden=f!=='mixed';$('dry-label').hidden=wetShare===1;$('wet-label').hidden=wetShare===0;$('dry').disabled=wetShare===1;$('wet').disabled=wetShare===0;$('split-label').textContent=$('split').value+'%';
const valid=$('pet-form').checkValidity();const blocked=$('goal').value!=='maintain'||$('health').value!=='healthy'||$('activity').value==='high';$('copy').disabled=!valid||blocked;$('share').hidden=!valid||blocked;
if(!valid||blocked){['calories','dry-out','wet-out','water-out'].forEach(id=>$(id).textContent='—');$('result-status').textContent=valid?'A personal feeding plan is best here.':'Check your food and weight entries.';$('guidance').textContent=valid?'For this goal or health situation, ask your veterinarian for a daily calorie target and suitable food portions. A general estimate would not account for your pet’s needs.':'Enter a positive weight and calorie values for the food being served. Results will return when all required numbers are valid.';shareText='';return;}
const kg=Number($('weight').value)/($('units').value==='lb'?2.2046226218:1);const stage=$('stage').value;let factor;if(stage!=='adult'){factor=pet==='cat'?2.5:stage==='young'?3:2;}else if($('activity').value==='low'){factor=pet==='cat'?1:1.4;}else{factor=pet==='cat'?($('neutered').value==='yes'?1.2:1.4):($('neutered').value==='yes'?1.6:1.8);}
const kcal=70*Math.pow(kg,.75)*factor;const dry=wetShare===1?0:kcal*(1-wetShare)/Number($('dry').value);const wet=wetShare===0?0:kcal*wetShare/Number($('wet').value)*100;const imperial=$('units').value==='lb';$('calories').textContent=Math.round(kcal);$('dry-out').textContent=dry.toFixed(2);$('wet-out').textContent=imperial?(wet/28.349523125).toFixed(1):Math.round(wet);$('wet-unit').textContent=imperial?'ounces / day':'grams / day';$('water-out').textContent=imperial?(kcal/29.57352956).toFixed(1)+' fl oz':Math.round(kcal)+' mL';$('result-status').textContent=initial?'Starting estimate · based on the example inputs':'Updated estimate · check your food label';$('guidance').textContent=stage==='adult'?'Daily totals, not per meal. Treats and extras count toward the calorie total.':'For healthy, weaned growing pets only. Check portions and growth with your vet; large dogs may grow beyond their first year.';
shareText=`FeedPetsWell ${pet} feeding estimate\n${Math.round(kcal)} kcal/day\nDry: ${dry.toFixed(2)} cups/day\nWet: ${$('wet-out').textContent} ${imperial?'oz':'g'}/day\nTotal water (food + drinking): ${$('water-out').textContent}\nEducational estimate, not a veterinary prescription.\nhttps://ctnb427-debug.github.io/FeedPetsWell/`;$('share').href='https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent('https://ctnb427-debug.github.io/FeedPetsWell/');}
document.querySelectorAll('[data-pet]').forEach(b=>b.addEventListener('click',()=>{pet=b.dataset.pet;document.querySelectorAll('[data-pet]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',x===b?'true':'false')});$('pet-label').textContent='FOR YOUR '+pet.toUpperCase();calculate();}));
$('units').addEventListener('change',()=>{const next=$('units').value;const v=Number($('weight').value);if(v>0&&next!==lastUnits)$('weight').value=(v*(next==='lb'?2.2046226218:1/2.2046226218)).toFixed(3);$('weight').max=next==='lb'?'440':'200';lastUnits=next;calculate();});
$('pet-form').addEventListener('input',e=>{if(e.target.id!=='units')calculate();$('copy-status').textContent='';});$('pet-form').addEventListener('change',()=>calculate());$('pet-form').addEventListener('submit',e=>{e.preventDefault();calculate();if(matchMedia('(max-width:700px)').matches)$('results').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth',block:'start'});});$('copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(shareText);$('copy-status').textContent='Estimate copied — ready to paste.';}catch(e){$('copy-status').textContent='Copy is unavailable in this browser. You can select and copy the results above.'}});calculate(true);
})();
